### ISSUE TITLE
Frequent prompts for Cloudflare verification

### ISSUE THREAD

**Issue by chanda** [lxfater/Portal#29]
It seems that due to a change in ChatGPT’s strategy, logging in via ChatGPTWeb will disconnect after a few minutes of inactivity ( Error warning: Cloudflare ), even though it used to work normally under the same network environment.

I use this plugin on the webpage to avoid disconnection: https://greasyfork.org/zh-CN/scripts/462967-chatgpt-heartbeat
Hope it can be fixed in the next version, thx !!

**Comment by lxfater** [comment]
OK



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 18, 2023 09:26 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [lxfater/Portal] Frequent prompts for Cloudflare verification (Issue#29)




 
It seems that due to a change in ChatGPT’s strategy, logging in via ChatGPTWeb will disconnect after a few minutes of inactivity ( Error warning: Cloudflare ), even though it used to work normally under the same network environment.
 
I use this plugin on the webpage to avoid disconnection: https://greasyfork.org/zh-CN/scripts/462967-chatgpt-heartbeat
 Hope it can be fixed in the next version, thx !!
